package coldstoragemonitoring;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Battery implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String sensorType;
   private java.lang.Double reading;
   private java.lang.String alert;

   public Battery()
   {
   }

   public java.lang.String getSensorType()
   {
      return this.sensorType;
   }

   public void setSensorType(java.lang.String sensorType)
   {
      this.sensorType = sensorType;
   }

   public java.lang.Double getReading()
   {
      return this.reading;
   }

   public void setReading(java.lang.Double reading)
   {
      this.reading = reading;
   }

   public java.lang.String getAlert()
   {
      return this.alert;
   }

   public void setAlert(java.lang.String alert)
   {
      this.alert = alert;
   }

   public Battery(java.lang.String sensorType, java.lang.Double reading,
         java.lang.String alert)
   {
      this.sensorType = sensorType;
      this.reading = reading;
      this.alert = alert;
   }

}