package coldstoragemonitoring;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Temperature implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String roomType;
   private java.lang.Double reading;
   private java.lang.String alert;

   private java.lang.Integer alertCount;

   public Temperature()
   {
   }

   public java.lang.String getRoomType()
   {
      return this.roomType;
   }

   public void setRoomType(java.lang.String roomType)
   {
      this.roomType = roomType;
   }

   public java.lang.Double getReading()
   {
      return this.reading;
   }

   public void setReading(java.lang.Double reading)
   {
      this.reading = reading;
   }

   public java.lang.String getAlert()
   {
      return this.alert;
   }

   public void setAlert(java.lang.String alert)
   {
      this.alert = alert;
   }

   public java.lang.Integer getAlertCount()
   {
      return this.alertCount;
   }

   public void setAlertCount(java.lang.Integer alertCount)
   {
      this.alertCount = alertCount;
   }

   public Temperature(java.lang.String roomType, java.lang.Double reading,
         java.lang.String alert, java.lang.Integer alertCount)
   {
      this.roomType = roomType;
      this.reading = reading;
      this.alert = alert;
      this.alertCount = alertCount;
   }

}